name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'   # latest LTS version of Node.js

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy
      if: success()  # only runs if tests pass
      run: |
        echo "Deploying app..."
        # Example: Copy files to a server via scp or run deployment scripts
        # scp -r ./ user@your-server:/path/to/app
